function nml2tr(nml,fout);

% writes triangle .node and .ele files based on nml structure

% do nodes
ind=1:length(nml.x);ind=ind';
f=fopen([fout '.node'],'w');
fprintf(f,'%d 2 1 0\n',length(nml.x));
fprintf(f,'%d %f %f %f\n',[ind-1 nml.x nml.y nml.z]');
fprintf(f,'# generated by nml2tri.m\n');
fclose(f);

% do elems
ind=1:length(nml.e);ind=ind';
f=fopen([fout '.ele'],'w');
fprintf(f,'%d 3 1 0\n',length(nml.e));
fprintf(f,'%d %d %d %d\n',[ind-1 nml.e(:,1)-1 nml.e(:,2)-1 nml.e(:,3)-1]');
fprintf(f,'# generated by nml2tri.m\n');
fclose(f);
